apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sc01-basic-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shaydevops2024/kubernetes-production-simulator.git
    targetRevision: HEAD
    path: argocd-scenarios/01-basic-app-deploy/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-sc-01
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
