apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sc08-multi-source
  namespace: argocd
  labels:
    scenario: "08"
    category: multi-source
spec:
  project: default
  source:
    repoURL: https://github.com/YOURUSER/YOURREPO.git
    targetRevision: HEAD
    path: argocd-scenarios/08-multi-source-app/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-sc-08
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
