apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sc05-kustomize-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shaydevops2024/kubernetes-production-simulator.git
    targetRevision: HEAD
    path: argocd-scenarios/05-kustomize-envs/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-sc-05-prod
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
