apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adopted-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adopted-app.labels" . | nindent 4 }}
    version: {{ .Values.appVersion | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adopted-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adopted-app.selectorLabels" . | nindent 8 }}
        version: {{ .Values.appVersion | quote }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
