apiVersion: v1
kind: Service
metadata:
  name: bluegreen-service
  namespace: k8s-multi-demo
spec:
  selector:
    app: bluegreen-demo
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
