apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sc11-canary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shaydevops2024/kubernetes-production-simulator.git
    targetRevision: HEAD
    path: argocd-scenarios/11-canary-rollout/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-sc-11
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
