apiVersion: v1
kind: Service
metadata:
  name: dr-service
  namespace: argocd-sc-12
  labels:
    app: dr-app
spec:
  selector:
    app: dr-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
