# k8s/base/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: k8s-multi-demo
  labels:
    app: k8s-demo-app
type: Opaque
data:
  SECRET_TOKEN: bXktc3VwZXItc2VjcmV0LXRva2VuLTEyMzQ1