apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sc07-rollback
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shaydevops2024/kubernetes-production-simulator.git
    targetRevision: HEAD
    path: argocd-scenarios/07-gitops-rollback/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-sc-07
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
